### ISSUE TITLE
Add new “Snapdragon game super resolution” sample!

### ISSUE THREAD

**Issue by oscarbg** [SnapdragonStudios/adreno-gpu-vulkan-code-sample-framework#7]
Hi,
reading recent rgsr introduction:

https://www.qualcomm.com/news/onq/2023/04/introducing-snapdragon-game-super-resolution

would like to ask more info about it..:
0)coming soon or released already?
1) the tech is open source or provided as precompiled library?
2) it’s under NDA or public download? In last case can provide download link location?
3) can add a simple sample on this repo using this tech and possible add also fsr and bilinear to compare perf/quality tradeoffs on the sample…

thanks..

**Comment by RodrigoHolztrattner-QuIC** [comment]
Hi @oscarbg ,

On its currently iteration it's under NDA, so unfortunately no download is available right now.

It's good to know that you are interested on a sample for this technique, I will make sure to forward this request internally!

**Comment by oscarbg** [comment]
@RodrigoHolztrattner-Qualcomm Thanks!

**Comment by RodrigoHolztrattner-QuIC** [comment]
Hi @oscarbg , just letting you know that a fresh Snapdragon GSR sample was added today (through PR https://github.com/quic/adreno-gpu-vulkan-code-sample-framework/pull/10)

We also released the shaders under BSD-3 at another repository a while ago: https://github.com/quic/snapdragon-gsr

I'm closing this issue since a sample is now available, feel free to open a new one in case you have questions, thank you!
